In [2]:
import pandas as pd

departments = pd.read_csv("departments.csv")
diagnosis = pd.read_csv("diagnosis.csv")
encounters = pd.read_csv("encounters.csv")
patients = pd.read_csv("patients.csv")
providers = pd.read_csv("providers.csv")
social_determinants = pd.read_csv("social_determinants.csv")
tigercensuscodes = pd.read_csv("tigercensuscodes.csv")

/var/folders/gp/m5jhv8y904l6263shvkxvlq40000gn/T/ipykernel_7057/229057041.py:8: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  social_determinants = pd.read_csv("social_determinants.csv")

## Null Values

In [14]:
print(departments.shape[0])
departments.isnull().sum()

11597

DepartmentKey             0
Address                2884
City                   2204
County                  574
DepartmentName            0
DepartmentSpecialty     574
DepartmentType          574
PostalCode             3009
CensusTract            4575
dtype: int64

In [20]:
departments.describe()

       DepartmentKey   CensusTract
count   11597.000000  7.022000e+03
mean     6323.080279  2.800299e+10
std      3892.646026  1.454756e+10
min        -3.000000  8.013013e+09
25%      2897.000000  2.017700e+10
50%      5796.000000  2.017700e+10
75%      9940.000000  2.017700e+10
max     12912.000000  5.507796e+10

In [13]:
print(diagnosis.shape[0])
diagnosis.isnull().sum()

1531262

DiagnosisKey      0
GroupName         0
GroupCode         0
DiagnosisName     0
DiagnosisValue    0
dtype: int64

In [21]:
diagnosis.describe()

       DiagnosisKey
count  1.531262e+06
mean   8.391665e+05
std    4.960558e+05
min    2.000000e+00
25%    3.706632e+05
50%    8.970705e+05
75%    1.274979e+06
max    1.629359e+06

In [12]:
print(encounters.shape[0])
encounters.isnull().sum()

7675801

Date                                 0
AdmissionInstant               6627001
AdmitYear                      6627001
AdmitMonth                     6627001
AdmitDay                       6627001
AdmitHour                      6627001
AdmitMinute                    6627001
AdmissionSource                   1400
AdmissionType                     1086
DischargeInstant               6627001
DischargeYear                  6627001
DischargeMonth                 6627001
DischargeDay                   6627001
DischargeHour                  6627001
DischargeMinute                6627001
EncounterKey                         0
PatientDurableKey                    0
Type                                 0
VisitType                            0
VisitTypeDescription                 0
ProviderDurableKey                   0
AttendingProviderDurableKey          0
DischargeProviderDurableKey          0
DepartmentKey                        0
PrimaryDiagnosisKey                  0
IsEdVisit                            0
IsHospitalAdmission                  0
IsHospitalOutpatientVisit            0
IsInpatientAdmission                 0
IsObservation                        0
IsOutpatientFaceToFaceVisit          0
dtype: int64

In [22]:
encounters.describe()

,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,DischargeYear,DischargeMonth,DischargeDay,DischargeHour,DischargeMinute,...,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
count,1.048800e+06,1.048800e+06,1.048800e+06,1.048800e+06,1.048800e+06,1.048800e+06,1.048800e+06,1.048800e+06,1.048800e+06,1.048800e+06,...,7.675801e+06,7.675801e+06,7.675801e+06,7.675801e+06,7.675801e+06,7.675801e+06,7.675801e+06,7.675801e+06,7.675801e+06,7.675801e+06
mean,2.023613e+03,6.588271e+00,1.573335e+01,1.132806e+01,2.912913e+01,2.023615e+03,6.588637e+00,1.573232e+01,1.816204e+01,4.457307e+01,...,1.480722e+04,6.062550e+03,2.560435e+03,5.563261e+05,3.406263e-02,1.295487e-02,8.055967e-02,1.102178e-02,1.985200e-03,5.772915e-01
std,1.093959e+00,3.436356e+00,8.735823e+00,4.687635e+00,1.844323e+01,1.094462e+00,3.436354e+00,8.734742e+00,6.148068e+00,1.923012e+01,...,6.654712e+04,4.158884e+04,4.498532e+03,4.482657e+05,1.813901e-01,1.130798e-01,2.721577e-01,1.044045e-01,4.451134e-02,4.939899e-01
min,2.022000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.022000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,...,-1.000000e+00,-1.000000e+00,2.000000e+01,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.023000e+03,4.000000e+00,8.000000e+00,8.000000e+00,1.300000e+01,2.023000e+03,4.000000e+00,8.000000e+00,1.300000e+01,3.000000e+01,...,-1.000000e+00,-1.000000e+00,1.600000e+02,9.124900e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.024000e+03,7.000000e+00,1.600000e+01,1.100000e+01,3.000000e+01,2.024000e+03,7.000000e+00,1.600000e+01,2.300000e+01,5.900000e+01,...,-1.000000e+00,-1.000000e+00,3.480000e+02,5.690550e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
75%,2.025000e+03,1.000000e+01,2.300000e+01,1.400000e+01,4.500000e+01,2.025000e+03,1.000000e+01,2.300000e+01,2.300000e+01,5.900000e+01,...,-1.000000e+00,-1.000000e+00,4.780000e+02,8.544710e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
max,2.025000e+03,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01,2.026000e+03,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01,...,5.005510e+05,4.984660e+05,1.280300e+04,1.629359e+06,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [11]:
print(patients.shape[0])
patients.isnull().sum()

947685

CensusBlockGroupFipsCode         0
DurableKey                       0
FirstRace                   365398
MaritalStatus                    0
MyChartStatus                    0
OmbEthnicity                     0
OmbRace                          0
SexAssignedAtBirth               0
SexualOrientation                0
SmokingStatus                    0
VitalStatus                      0
PatientBirthYearBin           1725
dtype: int64

In [24]:
# patients.describe

In [10]:
print(providers.shape[0])
providers.isnull().sum()

299075

DurableKey                0
ClinicianTitle       113067
OfficeAddress         30335
OfficeCity            30344
OfficePostalCode      30362
PrimaryDepartment         0
PrimarySpecialty      37856
Type                      0
dtype: int64

In [25]:
providers.describe()

          DurableKey
count  299075.000000
mean   257974.946348
std    146665.797512
min        -3.000000
25%    117370.500000
50%    304439.000000
75%    387415.500000
max    500329.000000

In [15]:
print(social_determinants.shape[0])
social_determinants.isnull().sum()

3977901

DisplayName                0
AnswerText                 0
EncounterKey               0
PatientDurableKey          0
Domain               2326196
dtype: int64

In [26]:
social_determinants.describe()

       EncounterKey  PatientDurableKey
count  3.977901e+06       3.977901e+06
mean   1.433564e+08       4.906481e+06
std    6.631894e+06       3.405559e+06
min    8.860317e+06       5.000000e+00
25%    1.385334e+08       6.712960e+05
50%    1.434377e+08       5.793106e+06
75%    1.488024e+08       7.076732e+06
max    1.544539e+08       1.119777e+07

In [16]:
print(tigercensuscodes.shape[0])
tigercensuscodes.isnull().sum()

2463

GEOID              0
PopulationValue    2
CENTLAT            2
CENTLON            2
dtype: int64

In [27]:
tigercensuscodes.describe()

              GEOID  PopulationValue      CENTLAT      CENTLON
count  2.463000e+03      2461.000000  2461.000000  2461.000000
mean   2.011979e+11      1193.774888    38.477591   -96.457459
std    5.808734e+08       545.065173     0.722984     1.741980
min    2.000195e+11         0.000000    37.007667  -101.917153
25%    2.009105e+11       819.000000    37.715626   -97.367228
50%    2.011379e+11      1077.000000    38.832777   -96.073752
75%    2.017301e+11      1462.000000    39.028955   -94.829251
max    2.020998e+11      4920.000000    39.948951   -94.609585

## Brief Analysis

In [29]:
encounters.

,Date,AdmissionInstant,AdmitYear,AdmitMonth,AdmitDay,AdmitHour,AdmitMinute,AdmissionSource,AdmissionType,DischargeInstant,...,AttendingProviderDurableKey,DischargeProviderDurableKey,DepartmentKey,PrimaryDiagnosisKey,IsEdVisit,IsHospitalAdmission,IsHospitalOutpatientVisit,IsInpatientAdmission,IsObservation,IsOutpatientFaceToFaceVisit
0,04/25/22,2022-04-25 20:33:00,2022.0,4.0,25.0,20.0,33.0,Non-Health Care Facility Point of Origin,Elective,2022-04-25 21:35:00,...,2982,2982,27,910699,0,1,0,0,1,0
1,04/29/22,2022-04-29 18:18:00,2022.0,4.0,29.0,18.0,18.0,Clinic/Physician Referral,Elective,2022-04-29 18:20:00,...,2979,2979,27,-1,0,1,0,0,1,0
2,01/10/22,2022-01-10 05:52:00,2022.0,1.0,10.0,5.0,52.0,Non-Health Care Facility Point of Origin,Elective,2022-01-12 11:43:00,...,6223,7015,27,468738,0,1,0,1,0,0
3,03/08/22,2022-03-08 09:08:00,2022.0,3.0,8.0,9.0,8.0,Non-Health Care Facility Point of Origin,Elective,2022-03-10 13:45:00,...,7973,7973,27,468492,0,1,0,1,0,0
4,03/16/22,2022-03-16 14:19:00,2022.0,3.0,16.0,14.0,19.0,Non-Health Care Facility Point of Origin,Elective,2022-03-16 16:00:00,...,6223,2982,27,907210,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7675796,12/29/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,18326,-1,57,858635,0,0,0,0,0,1
7675797,12/12/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,-1,-1,12707,-1,0,0,0,0,0,1
7675798,12/12/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,79382,-1,57,855970,0,0,0,0,0,1
7675799,08/20/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,1868,-1,11805,853446,0,0,0,0,0,0
7675800,07/17/25,NaN,NaN,NaN,NaN,NaN,NaN,*Not Applicable,*Not Applicable,NaN,...,1868,-1,11805,853446,0,0,0,0,0,0